### ISSUE TITLE
Methods replacing null with empty collections causes doublet fields

### ISSUE THREAD

**Issue by jskov-jyskebank-dk** [jskov/openapi-jaxrs-client#126]
Today the option `generator-use-empty-collections` replaced the normal getters with variants that translate null to empty collections.
And add a companion getter with a different name, that allows getting the raw property value (null or otherwise).

This causes problems when serializing (double properties).

The ideal code would be something like this:

```java
@Valid
public List getFoobar() {}

@Valid
@JsonIgnore
public List getFoobarReplacingNullWithEmptyCollection() {}
```
But we have a lot of existing code expecting the default getter to do the null-for-collection magic. 

Maybe add option to make naming the correct way.

And play with ignore-annotations to see if the existing code generation can be made to work (even if simple getter is ignored, the setter causes the field to be exposes double).

**Comment by jskov-jyskebank-dk** [comment]
@JsonIgnore is added to the long (getNullable) form as a workaround until a better solution can be found.

Note that this only affects Jackson. @JsonbTransient cannot be used on a getter if the property has other annotations (such as @JsonbProperty)

**Comment by jskov** [comment]
Accept current workaround, until specific problem can be reproduced.
