### ISSUE TITLE
Allow control of operation names - even when operationId provided

### ISSUE THREAD

**Issue by jskov-jyskebank-dk** [jskov/openapi-jaxrs-client#204]
The ACR API contains some operation ids that are not nice in Java, see https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/containerregistry/data-plane/Microsoft.ContainerRegistry/preview/2019-08-15/containerregistry.json

Maybe allow suppressing operationIds and using the synthetic input instead.

Or better, possibly, two set of naming rules - one applied when operationId is available, the other for the synthetic names.

**Comment by jskov** [comment]
Fixed in summer, forgot to close issue.
