### ISSUE TITLE
Option to include swagger basePath in all API @Paths

### ISSUE THREAD

**Issue by jskov-jyskebank-dk** [jskov/openapi-jaxrs-client#255]
For example:

```yaml
swagger: "2.0"
info:
  version: "3.38.0-01"
  title: "Nexus Repository Manager REST API"
basePath: "/service/rest/"
...
  /v1/components/{id}:
    post:
```
Spent some time not understading why the post did not work at `/v1/components` instead of `/service/rest/v1/components`

**Comment by jskov** [comment]
Was only possible in spec version 2.0, and is not exposes by 3.0 parser.

Spec 3.0 moves the field into part of server definitions - which means it is only relevant for a given endpoint (so not for API generation).
