### ISSUE TITLE
Path params should be @Encoded if not allowReserved

### ISSUE THREAD

**Issue by jskov-jyskebank-dk** [jskov/openapi-jaxrs-client#288]
https://swagger.io/docs/specification/describing-parameters/

Seen with

```
  /projects/{id}/tags/{tag}:
    get:
      tags:
      - Projects
      parameters:
      - name: id
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/ProjectId'
      - name: tag
        in: path
        required: true
        schema:
          type: string
 ```

where `tag` should really be annotated with @Encoded because it can contain the reserved character /.

**Comment by jskov** [comment]
This is not so easy.
The OpenApi spec only allows allowReserved on in- and query-params.

The lack of general handling of this encoding issue, it is clearly not a big or general problem.

So I will add an option that can contain a list of method:param targets that should be given the annotation.
Then it can at least be generated automatically, although it is outside the spec.

**Comment by jskov** [comment]
See https://github.com/jskov/openapi-jaxrs-client/tree/main/src/test/java/mada/tests/e2e/opts/generator/encoded

**Comment by jskov** [comment]
@Encoded not needed with Quarkus 3
