### ISSUE TITLE
Allow property description with type ref

### ISSUE THREAD

**Issue by lyngze** [jskov/openapi-jaxrs-client#391]
Currently including a description using the microprofile @Schema annotation with a description parameter changes the openapi spec from simple type ref to use allOf type ref like this

Without Schema annotation:
```
rolle:
    $ref: '#/components/schemas/RolleBeregnetEnum'
```

With `@Schema(description="Deltagerens rolle i koncernen. F.eks. om deltageren er debitor
    på koncernens engagement")`
```
rolle:
  description: Deltagerens rolle i koncernen. F.eks. om deltageren er debitor
    på koncernens engagement
  type: string
  allOf:
    - $ref: '#/components/schemas/RolleBeregnetEnum'
```

The last example should be a valid spec and have the same effect as the first + a property description. However this results in types being of String type rather than the refered type.

**Comment by jskov** [comment]
Fixed by #432

Unfortunately, it just reveals other problems with your openapi.yaml
